crawler:
  # URL of the site to crawl
  url: https://pastebin.com
  # where to save the paste content
  pastes_path: ../assets/pastes
  # time to repeat the action
  interval: 120

db:
  file: ../assets/db/pastes_db.json
  table: pastes


logger:
  name: PastebinCrawler
  level: INFO